# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven 

on:
  workflow_dispatch:
  

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ./graphical-app
      run: mvn -B package --file pom.xml

    - name: Run J-Link
      run: mvn javafx:jlink -f graphical-app/pom.xml

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-app
        path: |
          /home/runner/work/makeyourownapp-jam/makeyourownapp-jam/graphical-app/target/app
  
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file graphical-app/pom.xml

    - name: Run J-Link
      run: mvn javafx:jlink -f graphical-app/pom.xml
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: |
          D:\a\makeyourownapp-jam\makeyourownapp-jam\graphical-app\target\app
